# Generated by Django 3.2.9 on 2021-11-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(help_text='Ingrese su numero de Telefono', max_length=8, null=True),
        ),
    ]
