# Generated by Django 3.2.9 on 2021-11-07 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20211105_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_nombre', models.CharField(help_text='Ingrese el nombre de la serie novela o pelicula', max_length=100)),
                ('sipnosis', models.TextField(help_text='Ingrese la sipnosis de la novela o serie o pelicula')),
                ('author', models.CharField(help_text='Ingrese el nombre del autor', max_length=50)),
                ('nocap', models.IntegerField(help_text='Ingrese la cantidad de capitulos que tiene la pelicula o o serie')),
                ('img_presentacion', models.ImageField(default='img_presentacion/default.jpg', upload_to='img_presentacion/')),
                ('anio_lanza', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ingrese la categoria de la pelicula, serie o video, como niños, adultos, etc', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(help_text='Ingrese la clasificacion de la pelicula serie o novela, como A, B, C', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ingrese el tipo de catalogo como novela, serie, pelicula', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(help_text='Ingrese el numero de capitulo', max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('miniatura', models.ImageField(default='miniaturas/default.jpg', upload_to='miniaturas/')),
                ('idcatalog', models.ForeignKey(help_text='Ingrese el catalogo al que pertenece el video', on_delete=django.db.models.deletion.CASCADE, to='media.catalogovideo')),
            ],
        ),
        migrations.CreateModel(
            name='Visualizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(blank=True, help_text='Ingrese la hora en que termino de ver el video', max_length=4, null=True)),
                ('minuto', models.CharField(blank=True, help_text='Ingrese el minuto en que dejo de ver el video', max_length=4, null=True)),
                ('segundo', models.CharField(blank=True, help_text='Ingrese el segundo en que se quedo el video', max_length=4, null=True)),
                ('fecha_visualizacion', models.DateField(auto_now_add=True, help_text='Ingrese la fecha de visualizacion')),
                ('idusuario', models.ForeignKey(help_text='Ingrese el id del usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(help_text='Ingrese el Video a visualizar', on_delete=django.db.models.deletion.CASCADE, to='media.videos')),
            ],
        ),
        migrations.AddField(
            model_name='catalogovideo',
            name='idcategoria',
            field=models.ForeignKey(help_text='Ingrese el tipo de catalogo', on_delete=django.db.models.deletion.CASCADE, to='media.categoriacatalogo'),
        ),
        migrations.AddField(
            model_name='catalogovideo',
            name='idclasificacion',
            field=models.ForeignKey(help_text='Ingrese la clasificacion, del video', on_delete=django.db.models.deletion.CASCADE, to='media.clasificacioncatalogo'),
        ),
        migrations.AddField(
            model_name='catalogovideo',
            name='idtipo',
            field=models.ForeignKey(help_text='Ingrese el tipo de video', on_delete=django.db.models.deletion.CASCADE, to='media.tipocatalog'),
        ),
    ]
