# Generated by Django 3.2.9 on 2021-11-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20211107_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogovideo',
            name='img_presentacion',
            field=models.ImageField(default='img_pre/default.jpg', upload_to='img_pre/'),
        ),
    ]
