# Generated by Django 3.2.9 on 2021-11-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_catalogovideo_img_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='miniatura',
            field=models.ImageField(default='mini_img_video/default.jpg', upload_to='mini_img_video/'),
        ),
    ]
