# Generated by Django 3.2.9 on 2021-11-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_videos_miniatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogovideo',
            name='img_presentacion',
            field=models.ImageField(upload_to='img_pre'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='miniatura',
            field=models.ImageField(upload_to='mini_img_video'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
