# Generated by Django 3.2.9 on 2021-11-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20211107_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporadaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(help_text='Ingrese el numero de temporada', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='idtemporada',
            field=models.ForeignKey(help_text='Ingrese la temporada del video', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.temporadavideo'),
        ),
    ]
