# Generated by Django 3.2.9 on 2021-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20211107_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovideo',
            name='videotriller',
            field=models.FileField(null=True, upload_to='video_triller'),
        ),
    ]
