# Generated by Django 3.2.9 on 2021-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_catalogovideo_videotriller'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovideo',
            name='url',
            field=models.SlugField(blank=True, help_text='url del catalogo', max_length=200, null=True),
        ),
    ]
