# Generated by Django 3.2.9 on 2021-11-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_catalogovideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovideo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
