# Generated by Django 3.2.9 on 2021-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_catalogovideo_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovideo',
            name='urlencrip',
            field=models.TextField(blank=True, help_text='ingrese la url encriptada', null=True),
        ),
    ]
