# Generated by Django 3.2.9 on 2021-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_catalogovideo_urlencrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ingrese el nombre del video', max_length=50, null=True),
        ),
    ]
